# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RddQ53fm-cm3xEgu0dh6aGSnSQThTgKX
"""

import matplotlib.pyplot as plt
import numpy as np

def lissajous(desfase, v_desfase):
  nsides=5
  theta=np.linspace(0,2*np.pi,200)
  figure= plt.figure(figsize=(5,6))
  figure.suptitle("DESFASE = " + str(desfase))

  k=0
  for i in range(1,6):
    angulo_x= i*theta
    k +=i-1
    for j in range(i,6):
      angulo_y = j*theta
      k +=1
      ax1= figure.add_subplot(nsides,nsides,k)
      ax1.plot(np.sin(angulo_x), np.sin(angulo_y + v_desfase))
      plt.axis("off")
desfase=np.array(["0", "n/4", "n/2" ])
v_desfase =np.array([0, np.pi/4, np.pi/2])
for z in range(0,3):
  lissajous(desfase[z], v_desfase[z])

plt.show()